spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username:
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG



cloud:
  aws:
    credentials:
      accessKey: { }       # AWS IAM AccessKey 적기
      secretKey: { }   # AWS IAM SecretKey 적기
    s3:
      bucket: {  }    # ex) marryting-gyunny
    region:
      static: 
    stack:
      auto: false
