spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:

  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG