spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test


  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

cloud:
  aws:
    credentials:
      access-key: #엑서스 키
      secret-key: # 엑서스 시크릿 키
    s3:
      bucket: #버킷 이름
    region:
      static: "ap-northeast-2" #지역
    stack:
      auto: false